#import <Foundation/Foundation.h>
#import "SWGEmptyObject.h"
#import "SWGInlineResponse200.h"
#import "SWGProtocol.h"

/**
* Test Mock
* 个人测试空间 Mock 专用
*
* OpenAPI spec version: last
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGApi: NSObject <SWGProtocol>

extern NSString* kSWGApiErrorDomain;
extern NSInteger kSWGApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// test_mock_1_basic
/// 
///
/// @param param1 testing params
/// 
///  code:200 message:"successful operation"
///
/// @return SWGInlineResponse200*
-(NSURLSessionTask*) mockGetWithParam1: (NSString*) param1
    completionHandler: (void (^)(SWGInlineResponse200* output, NSError* error)) handler;


/// test_mock_multi_params
/// 
///
/// @param param1 
/// @param param2 
/// 
///  code:200 message:"successful operation"
///
/// @return SWGEmptyObject*
-(NSURLSessionTask*) testMockMultiGetWithParam1: (NSString*) param1
    param2: (NSString*) param2
    completionHandler: (void (^)(SWGEmptyObject* output, NSError* error)) handler;



@end
