/**
 * Test Mock
 * 个人测试空间 Mock 专用
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param resultParam1 mock.js demo
 * @param resultParam2 mock.js demo
 * @param resultParam3 json schema demo
 * @param resultParam4 
 * @param resultParam5 
 */
data class Empty_object (

    /* mock.js demo */
    val resultParam1: kotlin.String,
    /* mock.js demo */
    val resultParam2: kotlin.String,
    /* json schema demo */
    val resultParam3: kotlin.String,
    val resultParam4: kotlin.String,
    val resultParam5: Empty_object.ResultParam5
) {
    /**
    * 
    * Values: _01,_02,_03,_04
    */
    enum class ResultParam5(val value: kotlin.String){
        _01("ENUM_CASE_01"),
        _02("ENUM_CASE_02"),
        _03("ENUM_CASE_03"),
        _04("ENUM_CASE_04");
    }
}