//
// EmptyObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmptyObject: Codable {

    public var field1: String
    public var field2: [String]

    public init(field1: String, field2: [String]) {
        self.field1 = field1
        self.field2 = field2
    }

    public enum CodingKeys: String, CodingKey { 
        case field1 = "field_1"
        case field2 = "field_2"
    }


}

