//
// InlineResponse200TestParam2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200TestParam2: Codable {

    public var testParam3: Bool

    public init(testParam3: Bool) {
        self.testParam3 = testParam3
    }

    public enum CodingKeys: String, CodingKey { 
        case testParam3 = "test_param_3"
    }


}

