//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var testParam1: String
    public var testParam2: InlineResponse200TestParam2

    public init(testParam1: String, testParam2: InlineResponse200TestParam2) {
        self.testParam1 = testParam1
        self.testParam2 = testParam2
    }

    public enum CodingKeys: String, CodingKey { 
        case testParam1 = "test_param_1"
        case testParam2 = "test_param_2"
    }


}

