/**
 * Test Mock
 * 个人测试空间 Mock 专用
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.InlineResponse200TestParam2

/**
 * 
 * @param testParam1 
 * @param testParam2 
 */
data class InlineResponse200 (

    val testParam1: kotlin.String,
    val testParam2: InlineResponse200TestParam2
) {
}