#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Test Mock
* 个人测试空间 Mock 专用
*
* OpenAPI spec version: last
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGEmptyObject
@end

@interface SWGEmptyObject : SWGObject


@property(nonatomic) NSString* field1;

@property(nonatomic) NSArray<NSString*>* field2;

@end
