#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Test Mock
* 个人测试空间 Mock 专用
*
* OpenAPI spec version: last
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SWGInlineResponse200TestParam2.h"
@protocol SWGInlineResponse200TestParam2;
@class SWGInlineResponse200TestParam2;



@protocol SWGInlineResponse200
@end

@interface SWGInlineResponse200 : SWGObject


@property(nonatomic) NSString* testParam1;

@property(nonatomic) SWGInlineResponse200TestParam2* testParam2;

@end
