#import <Foundation/Foundation.h>
#import <JSONModel/JSONModel.h>

/**
* Test Mock
* 个人测试空间 Mock 专用
*
* OpenAPI spec version: last
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@interface SWGObject : JSONModel

@end
